defaults:
  - _self_
  - shared
  - data: main
  - model: ???
  - optimizer: adam
  - scheduler: multi_step_lr
  - metrics

train_dataset: ???
valid_dataset:
epochs: 15
snapshot_interval: 1
start_epoch: 0
experiment_name: Default
experiment_tag:
mlflow_tracking_uri:
train_epu: False
epu_model_path: ???
n_clusters: 17
dataset_name: ???
lstm:
  alpha: 0.001
  optimizer: adam
  scheduler: tri
  lr: 0.0001
  lr_decay: 0.99
  epochs: 200
dc:
  lr: 0.0005
  lr_decay: 0.98
  weight_decay: 0.00001
  gamma:  0.6
  epochs: 30
  stop_cret:  0.001
  update_interval:  2.0
  alpha: 0.001 # equal to lstm.alpha
