defaults:
  - _self_
  - common

type: deposit

device: ${device}
target_dim: 96

config:
  target_dim: 96
  diffusion:
    layers: 4
    channels: 64
    nheads: 8
    diffusion_embedding_dim: 128
    beta_start: 0.0001
    beta_end: 0.5
    num_steps: 50
    schedule: 'cosine'
    type: 'ddpm' # or ddim
    side_dim: -1
  model:
    is_unconditional: 0
    timeemb: 128
    featureemb: 16

loss:
  type: deposit_loss
